-- Run this in the Supabase SQL editor for Records

create table if not exists public.review_comments (
  id bigint generated by default as identity primary key,
  review_type text not null check (review_type in ('song', 'album', 'artist')),
  review_id bigint not null,
  user_id uuid references auth.users (id) on delete set null,
  username text not null default 'Anonymous',
  comment text not null,
  created_at timestamptz not null default now()
);

create index if not exists review_comments_lookup_idx
  on public.review_comments (review_type, review_id, created_at desc);

create table if not exists public.follows (
  id bigint generated by default as identity primary key,
  follower_id uuid not null references auth.users (id) on delete cascade,
  following_id uuid not null references auth.users (id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (follower_id, following_id),
  check (follower_id <> following_id)
);

create index if not exists follows_follower_idx
  on public.follows (follower_id, created_at desc);

create index if not exists follows_following_idx
  on public.follows (following_id, created_at desc);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  actor_id uuid references auth.users (id) on delete set null,
  actor_username text,
  type text not null check (type in ('like', 'comment', 'follow', 'review')),
  message text not null,
  review_type text check (review_type in ('song', 'album', 'artist')),
  review_id bigint,
  link text,
  read boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists notifications_user_idx
  on public.notifications (user_id, read, created_at desc);

alter table public.review_comments enable row level security;
alter table public.follows enable row level security;
alter table public.notifications enable row level security;

create policy "review_comments are readable by everyone"
  on public.review_comments for select using (true);

create policy "review_comments can be created by anyone"
  on public.review_comments for insert with check (true);

create policy "follows are readable by everyone"
  on public.follows for select using (true);

create policy "follows can be created"
  on public.follows for insert with check (true);

create policy "follows can be deleted"
  on public.follows for delete using (true);

create policy "notifications readable by owner"
  on public.notifications for select using (true);

create policy "notifications can be created"
  on public.notifications for insert with check (true);

create policy "notifications can be updated"
  on public.notifications for update using (true);
