-- Run this in the Supabase SQL editor for Records.
-- Safe to re-run: tables use IF NOT EXISTS, and policies are dropped before recreate.

create table if not exists public.profiles (
  id uuid primary key references auth.users (id) on delete cascade,
  username text not null default 'Anonymous',
  avatar_url text,
  bio text,
  updated_at timestamptz not null default now()
);

create index if not exists profiles_username_idx
  on public.profiles (username);

create table if not exists public.reviews (
  id bigint generated by default as identity primary key,
  song_name text not null,
  artist text,
  album text,
  image text,
  spotify text,
  rating numeric(3, 1) not null default 0 check (rating >= 0 and rating <= 10),
  review text not null,
  username text not null default 'Anonymous',
  user_id uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists reviews_song_idx
  on public.reviews (song_name, created_at desc);

create index if not exists reviews_user_idx
  on public.reviews (user_id, created_at desc);

create table if not exists public.album_reviews (
  id bigint generated by default as identity primary key,
  album_name text not null,
  artist text,
  image text,
  spotify text,
  rating numeric(3, 1) not null default 0 check (rating >= 0 and rating <= 10),
  review text not null,
  username text not null default 'Anonymous',
  user_id uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists album_reviews_album_idx
  on public.album_reviews (album_name, created_at desc);

create index if not exists album_reviews_user_idx
  on public.album_reviews (user_id, created_at desc);

create table if not exists public.artist_reviews (
  id bigint generated by default as identity primary key,
  artist_name text not null,
  image text,
  spotify text,
  rating numeric(3, 1) not null default 0 check (rating >= 0 and rating <= 10),
  review text not null,
  username text not null default 'Anonymous',
  user_id uuid references auth.users (id) on delete set null,
  created_at timestamptz not null default now()
);

create index if not exists artist_reviews_artist_idx
  on public.artist_reviews (artist_name, created_at desc);

create index if not exists artist_reviews_user_idx
  on public.artist_reviews (user_id, created_at desc);

create table if not exists public.review_likes (
  id bigint generated by default as identity primary key,
  review_type text not null check (review_type in ('song', 'album', 'artist')),
  review_id bigint not null,
  user_id uuid not null references auth.users (id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (review_type, review_id, user_id)
);

create index if not exists review_likes_lookup_idx
  on public.review_likes (review_type, review_id, created_at desc);

create table if not exists public.review_comments (
  id bigint generated by default as identity primary key,
  review_type text not null check (review_type in ('song', 'album', 'artist')),
  review_id bigint not null,
  user_id uuid references auth.users (id) on delete set null,
  username text not null default 'Anonymous',
  comment text not null,
  created_at timestamptz not null default now()
);

create index if not exists review_comments_lookup_idx
  on public.review_comments (review_type, review_id, created_at desc);

create table if not exists public.follows (
  id bigint generated by default as identity primary key,
  follower_id uuid not null references auth.users (id) on delete cascade,
  following_id uuid not null references auth.users (id) on delete cascade,
  created_at timestamptz not null default now(),
  unique (follower_id, following_id),
  check (follower_id <> following_id)
);

create index if not exists follows_follower_idx
  on public.follows (follower_id, created_at desc);

create index if not exists follows_following_idx
  on public.follows (following_id, created_at desc);

create table if not exists public.notifications (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users (id) on delete cascade,
  actor_id uuid references auth.users (id) on delete set null,
  actor_username text,
  type text not null check (type in ('like', 'comment', 'follow', 'review')),
  message text not null,
  review_type text check (review_type in ('song', 'album', 'artist')),
  review_id bigint,
  link text,
  read boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists notifications_user_idx
  on public.notifications (user_id, read, created_at desc);

-- API routes call Supabase with the publishable/anon key, so these policies
-- stay open. Tighten them only if those routes start sending the user JWT.
alter table public.profiles enable row level security;
alter table public.reviews enable row level security;
alter table public.album_reviews enable row level security;
alter table public.artist_reviews enable row level security;
alter table public.review_likes enable row level security;
alter table public.review_comments enable row level security;
alter table public.follows enable row level security;
alter table public.notifications enable row level security;

drop policy if exists "profiles are readable by everyone" on public.profiles;
create policy "profiles are readable by everyone"
  on public.profiles for select using (true);

drop policy if exists "profiles can be created" on public.profiles;
create policy "profiles can be created"
  on public.profiles for insert with check (true);

drop policy if exists "profiles can be updated" on public.profiles;
create policy "profiles can be updated"
  on public.profiles for update using (true);

drop policy if exists "reviews are readable by everyone" on public.reviews;
create policy "reviews are readable by everyone"
  on public.reviews for select using (true);

drop policy if exists "reviews can be created" on public.reviews;
create policy "reviews can be created"
  on public.reviews for insert with check (true);

drop policy if exists "reviews can be updated" on public.reviews;
create policy "reviews can be updated"
  on public.reviews for update using (true);

drop policy if exists "reviews can be deleted" on public.reviews;
create policy "reviews can be deleted"
  on public.reviews for delete using (true);

drop policy if exists "album_reviews are readable by everyone" on public.album_reviews;
create policy "album_reviews are readable by everyone"
  on public.album_reviews for select using (true);

drop policy if exists "album_reviews can be created" on public.album_reviews;
create policy "album_reviews can be created"
  on public.album_reviews for insert with check (true);

drop policy if exists "album_reviews can be updated" on public.album_reviews;
create policy "album_reviews can be updated"
  on public.album_reviews for update using (true);

drop policy if exists "album_reviews can be deleted" on public.album_reviews;
create policy "album_reviews can be deleted"
  on public.album_reviews for delete using (true);

drop policy if exists "artist_reviews are readable by everyone" on public.artist_reviews;
create policy "artist_reviews are readable by everyone"
  on public.artist_reviews for select using (true);

drop policy if exists "artist_reviews can be created" on public.artist_reviews;
create policy "artist_reviews can be created"
  on public.artist_reviews for insert with check (true);

drop policy if exists "artist_reviews can be updated" on public.artist_reviews;
create policy "artist_reviews can be updated"
  on public.artist_reviews for update using (true);

drop policy if exists "artist_reviews can be deleted" on public.artist_reviews;
create policy "artist_reviews can be deleted"
  on public.artist_reviews for delete using (true);

drop policy if exists "review_likes are readable by everyone" on public.review_likes;
create policy "review_likes are readable by everyone"
  on public.review_likes for select using (true);

drop policy if exists "review_likes can be created" on public.review_likes;
create policy "review_likes can be created"
  on public.review_likes for insert with check (true);

drop policy if exists "review_likes can be deleted" on public.review_likes;
create policy "review_likes can be deleted"
  on public.review_likes for delete using (true);

drop policy if exists "review_comments are readable by everyone" on public.review_comments;
create policy "review_comments are readable by everyone"
  on public.review_comments for select using (true);

drop policy if exists "review_comments can be created by anyone" on public.review_comments;
create policy "review_comments can be created by anyone"
  on public.review_comments for insert with check (true);

drop policy if exists "follows are readable by everyone" on public.follows;
create policy "follows are readable by everyone"
  on public.follows for select using (true);

drop policy if exists "follows can be created" on public.follows;
create policy "follows can be created"
  on public.follows for insert with check (true);

drop policy if exists "follows can be deleted" on public.follows;
create policy "follows can be deleted"
  on public.follows for delete using (true);

drop policy if exists "notifications readable by owner" on public.notifications;
create policy "notifications readable by owner"
  on public.notifications for select using (true);

drop policy if exists "notifications can be created" on public.notifications;
create policy "notifications can be created"
  on public.notifications for insert with check (true);

drop policy if exists "notifications can be updated" on public.notifications;
create policy "notifications can be updated"
  on public.notifications for update using (true);

drop policy if exists "notifications can be deleted" on public.notifications;
create policy "notifications can be deleted"
  on public.notifications for delete using (true);

grant select, insert, update, delete on
  public.profiles,
  public.reviews,
  public.album_reviews,
  public.artist_reviews,
  public.review_likes,
  public.review_comments,
  public.follows,
  public.notifications
to anon, authenticated, service_role;

grant usage, select on all sequences in schema public to anon, authenticated, service_role;

-- Create a profile row whenever someone signs up.
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.profiles (id, username)
  values (
    new.id,
    coalesce(nullif(trim(new.raw_user_meta_data->>'username'), ''), 'Anonymous')
  )
  on conflict (id) do nothing;

  return new;
end;
$$;

revoke all on function public.handle_new_user() from public, anon, authenticated;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

insert into public.profiles (id, username)
select
  id,
  coalesce(nullif(trim(raw_user_meta_data->>'username'), ''), 'Anonymous')
from auth.users
on conflict (id) do nothing;

-- Public avatars bucket. Uploads go to {userId}/{filename}.
insert into storage.buckets (id, name, public)
values ('avatars', 'avatars', true)
on conflict (id) do update set public = excluded.public;

drop policy if exists "avatars are publicly readable" on storage.objects;
create policy "avatars are publicly readable"
  on storage.objects for select
  using (bucket_id = 'avatars');

drop policy if exists "users can upload their own avatar" on storage.objects;
create policy "users can upload their own avatar"
  on storage.objects for insert
  with check (
    bucket_id = 'avatars'
    and auth.role() = 'authenticated'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists "users can update their own avatar" on storage.objects;
create policy "users can update their own avatar"
  on storage.objects for update
  using (
    bucket_id = 'avatars'
    and auth.role() = 'authenticated'
    and (storage.foldername(name))[1] = auth.uid()::text
  );

drop policy if exists "users can delete their own avatar" on storage.objects;
create policy "users can delete their own avatar"
  on storage.objects for delete
  using (
    bucket_id = 'avatars'
    and auth.role() = 'authenticated'
    and (storage.foldername(name))[1] = auth.uid()::text
  );
